// Auto-updating "National Day" data — keyed by MMDD (e.g. "0313" = March 13).
// Source: national_days.csv (district-provided). Bundled so the signage block
// works offline and needs no database lookup.
export const NATIONAL_DAYS: Record<string, string> = {
  "0101": "New Year's Day",
  "0102": "National Science Fiction Day",
  "0103": "National Fruitcake Toss Day",
  "0104": "National Trivia Day",
  "0105": "National Bird Day",
  "0106": "National Technology Day",
  "0107": "National Bobblehead Day",
  "0108": "National Bubble Bath Day",
  "0109": "National Law Enforcement Appreciation Day",
  "0110": "National Save The Eagles Day",
  "0111": "National Step in a Puddle and Splash Your Friends Day",
  "0112": "National Pharmacist Day",
  "0113": "National Rubber Duck Day",
  "0114": "National Dress Up Your Pet Day",
  "0115": "National Hat Day",
  "0116": "National Religious Freedom Day",
  "0117": "National Bootlegger's Day",
  "0118": "National Thesaurus Day",
  "0119": "National Popcorn Day",
  "0120": "National Buttercrunch Day",
  "0121": "National Granola Bar Day",
  "0122": "National Blonde Brownie Day",
  "0123": "National Handwriting Day",
  "0124": "National Compliment Day",
  "0125": "National Opposite Day",
  "0126": "National Peanut Brittle Day",
  "0127": "National Chocolate Cake Day",
  "0128": "National Blueberry Pancake Day",
  "0129": "National Puzzle Day",
  "0130": "National Croissant Day",
  "0131": "National Hot Chocolate Day",
  "0201": "National Serpent Day",
  "0202": "National Groundhog Day",
  "0203": "National Women Physicians Day",
  "0204": "National Thank a Mail Carrier Day",
  "0205": "National Weatherperson's Day",
  "0206": "National Frozen Yogurt Day",
  "0207": "National Periodic Table Day",
  "0208": "National Kite Flying Day",
  "0209": "National Pizza Day",
  "0210": "National Umbrella Day",
  "0211": "National Inventors' Day",
  "0212": "National Plum Pudding Day",
  "0213": "National Cheddar Day",
  "0214": "National Organ Donor Day",
  "0215": "National Gumdrop Day",
  "0216": "National Do a Grouch a Favor Day",
  "0217": "National Random Acts of Kindness Day",
  "0218": "National Battery Day",
  "0219": "National Chocolate Mint Day",
  "0220": "National Love Your Pet Day",
  "0221": "National Sticky Bun Day",
  "0222": "National Cook a Sweet Potato Day",
  "0223": "National Banana Bread Day",
  "0224": "National Tortilla Chip Day",
  "0225": "National Chocolate Covered Nut Day",
  "0226": "National Tell a Fairy Tale Day",
  "0227": "National Pokemon Day",
  "0228": "National Tooth Fairy Day",
  "0229": "National Leap Day",
  "0301": "National Horse Protection Day",
  "0302": "National Dr. Seuss Day",
  "0303": "National Anthem Day",
  "0304": "National Grammar Day",
  "0305": "National Cheese Doodle Day",
  "0306": "National Dentist's Day",
  "0307": "National Be Heard Day",
  "0308": "International Women's Day",
  "0309": "National Meatball Day",
  "0310": "National Mario Day",
  "0311": "National Promposal Day",
  "0312": "National Plant a Flower Day",
  "0313": "National Good Samaritan Day",
  "0314": "National Children's Craft Day",
  "0315": "National Shoe the World Day",
  "0316": "National Freedom of Information Day",
  "0317": "St. Patrick's Day",
  "0318": "National Sloppy Joe Day",
  "0319": "National Certified Nurses Day",
  "0320": "National Ravioli Day",
  "0321": "National Common Courtesy Day",
  "0322": "National Bavarian Crepes Day",
  "0323": "National Puppy Day",
  "0324": "National Chocolate Covered Raisin Day",
  "0325": "National Tolkien Reading Day",
  "0326": "National Spinach Day",
  "0327": "National Scribble Day",
  "0328": "National Something on a Stick Day",
  "0329": "National Mom and Pop Business Owners Day",
  "0330": "National Take a Walk in the Park Day",
  "0331": "National Crayon Day",
  "0401": "April Fools Day",
  "0402": "National Peanut Butter and Jelly Day",
  "0403": "National Find a Rainbow Day",
  "0404": "National School Librarian Day",
  "0405": "National Deep Dish Pizza Day",
  "0406": "National Student-Athlete Day",
  "0407": "National Handmade Day",
  "0408": "National Zoo Lovers Day",
  "0409": "National Unicorn Day",
  "0410": "National Farm Animals Day",
  "0411": "National Pet Day",
  "0412": "National Grilled Cheese Sandwich Day",
  "0413": "National Scrabble Day",
  "0414": "National Reach as High as You Can Day",
  "0415": "National Take a Wild Guess Day",
  "0416": "National Wear Your Pajamas to Work Day",
  "0417": "National Haiku Poetry Day",
  "0418": "National Animal Crackers Day",
  "0419": "National Hanging Out Day",
  "0420": "National Look Alike Day",
  "0421": "National Kindergarten Day",
  "0422": "National Earth Day",
  "0423": "National Lost Dogs Awareness Day",
  "0424": "National Pigs in a Blanket Day",
  "0425": "National Telephone Day",
  "0426": "National Pretzel Day",
  "0427": "National Tell a Story Day",
  "0428": "National Superhero Day",
  "0429": "National Zipper Day",
  "0430": "National Bugs Bunny Day",
  "0501": "School Principals' Day",
  "0502": "Free Comic Book Day",
  "0503": "National Paranormal Day",
  "0504": "National Star Wars Day",
  "0505": "National Astronaut Day",
  "0506": "National Nurses Day",
  "0507": "National Roast Leg of Lamb Day",
  "0508": "National Student Nurse Day",
  "0509": "National Sleepover Day",
  "0510": "National Clean Up Your Room Day",
  "0511": "National Twilight Zone Day",
  "0512": "National Nutty Fudge Day",
  "0513": "National Apple Pie Day",
  "0514": "National Dance Like a Chicken Day",
  "0515": "National Chocolate Chip Day",
  "0516": "National Do Something Good for Your Neighbor Day",
  "0517": "National Graduation Tassel Day",
  "0518": "National Visit Your Relatives Day",
  "0519": "National Devil's Food Cake Day",
  "0520": "National Rescue Dog Day",
  "0521": "National American Red Cross Founder's Day",
  "0522": "National Vanilla Pudding Day",
  "0523": "National Lucky Penny Day",
  "0524": "National Scavenger Hunt Day",
  "0525": "National Missing Children's Day",
  "0526": "National Paper Airplane Day",
  "0527": "National Grape Popsicle Day",
  "0528": "National Hamburger Day",
  "0529": "National Paperclip Day",
  "0530": "National Creativity Day",
  "0531": "National Smile Day",
  "0601": "National Say Something Nice Day",
  "0602": "National Rocky Road Day",
  "0603": "National Egg Day",
  "0604": "National Cheese Day",
  "0605": "National Gingerbread Day",
  "0606": "National Higher Education Day",
  "0607": "National Chocolate Ice Cream Day",
  "0608": "National Best Friends Day",
  "0609": "National Donald Duck Day",
  "0610": "National Ballpoint Pen Day",
  "0611": "National Corn on the Cob Day",
  "0612": "National Jerky Day",
  "0613": "National Weed Your Garden Day",
  "0614": "National Flag Day",
  "0615": "National Smile Power Day",
  "0616": "National Fudge Day",
  "0617": "National Eat Your Vegetables Day",
  "0618": "National Go Fishing Day",
  "0619": "National Garfield the Cat Day",
  "0620": "National Ice Cream Soda Day",
  "0621": "National Selfie Day",
  "0622": "National Onion Rings Day",
  "0623": "National Pink Day",
  "0624": "National Pralines Day",
  "0625": "National Catfish Day",
  "0626": "National Chocolate Pudding Day",
  "0627": "National Sunglasses Day",
  "0628": "National Paul Bunyan Day",
  "0629": "National Camera Day",
  "0630": "National OOTD Day",
  "0701": "National Postal Worker Day",
  "0702": "National I Forgot Day",
  "0703": "National Eat Your Beans Day",
  "0704": "National Barbecued Spareribs Day",
  "0705": "National Graham Cracker Day",
  "0706": "National Fried Chicken Day",
  "0707": "National Macaroni Day",
  "0708": "National Chocolate with Almonds Day",
  "0709": "National Sugar Cookie Day",
  "0710": "National Kitten Day",
  "0711": "National Blueberry Muffin Day",
  "0712": "National Simplicity Day",
  "0713": "National French Fry Day",
  "0714": "National Mac & Cheese Day",
  "0715": "National Give Something Away Day",
  "0716": "National Corn Fritters Day",
  "0717": "World Emoji Day",
  "0718": "National Sour Candy Day",
  "0719": "National Flitch Day",
  "0720": "National Moon Day",
  "0721": "National Be Someone Day",
  "0722": "National Hammock Day",
  "0723": "National Vanilla Ice Cream Day",
  "0724": "National Drive-Thru Day",
  "0725": "National Merry-Go-Round Day",
  "0726": "National Aunt and Uncle's Day",
  "0727": "National Creme Brulee Day",
  "0728": "National Milk Chocolate Day",
  "0729": "National Chicken Wing Day",
  "0730": "National Cheesecake Day",
  "0731": "National Avocado Day",
  "0801": "National Raspberry Cream Pie Day",
  "0802": "National Ice Cream Sandwich Day",
  "0803": "National Watermelon Day",
  "0804": "National Coast Guard Day",
  "0805": "National Oyster Day",
  "0806": "National Wiggle Your Toes Day",
  "0807": "National Lighthouse Day",
  "0808": "National Happiness Happens Day",
  "0809": "National Book Lovers Day",
  "0810": "National S'mores Day",
  "0811": "National Son's and Daughter's Day",
  "0812": "National Vinyl Record Day",
  "0813": "National Filet Mignon Day",
  "0814": "National Creamsicle Day",
  "0815": "National Relaxation Day",
  "0816": "National Tell a Joke Day",
  "0817": "National Thrift Shop Day",
  "0818": "National Fajita Day",
  "0819": "National Aviation Day",
  "0820": "National Radio Day",
  "0821": "National Senior Citizens Day",
  "0822": "National Be An Angel Day",
  "0823": "National Sponge Cake Day",
  "0824": "National Waffle Day",
  "0825": "National Park Service Founders Day",
  "0826": "National Women's Equality Day",
  "0827": "National Just Because Day",
  "0828": "National Power Rangers Day",
  "0829": "National Chop Suey Day",
  "0830": "National Beach Day",
  "0831": "National Trail Mix Day",
  "0901": "National No Rhyme (Nor Reason) Day",
  "0902": "National Blueberry Popsicle Day",
  "0903": "National Welsh Rarebit Day",
  "0904": "National Wildlife Day",
  "0905": "National Cheese Pizza Day",
  "0906": "National Read a Book Day",
  "0907": "National Salami Day",
  "0908": "National Ampersand Day",
  "0909": "National Teddy Bear Day",
  "0910": "National TV Dinner Day",
  "0911": "National Make Your Bed Day",
  "0912": "National Video Games Day",
  "0913": "National Peanut Day",
  "0914": "National Live Creative Day",
  "0915": "National Tackle Kids Cancer Day",
  "0916": "National Play-Doh Day",
  "0917": "National Apple Dumpling Day",
  "0918": "National Cheeseburger Day",
  "0919": "Talk Like a Pirate Day",
  "0920": "National Pepperoni Pizza Day",
  "0921": "National Pecan Cookie Day",
  "0922": "National Ice Cream Cone Day",
  "0923": "National Snack Stick Day",
  "0924": "National Punctuation Day",
  "0925": "National Comic Book Day",
  "0926": "National Dumpling Day",
  "0927": "National Scarf Day",
  "0928": "National Strawberry Cream Pie Day",
  "0929": "National Coffee Day",
  "0930": "National Chewing Gum Day",
  "1001": "National Homemade Cookies Day",
  "1002": "National Custodial Worker's Recognition Day",
  "1003": "National Techies Day",
  "1004": "World Smile Day",
  "1005": "National Do Something Nice Day",
  "1006": "National Coaches Day",
  "1007": "National LED Light Day",
  "1008": "National Pierogi Day",
  "1009": "National Moldy Cheese Day",
  "1010": "World Mental Health Day",
  "1011": "National Sausage Pizza Day",
  "1012": "National Savings Day",
  "1013": "National Train Your Brain Day",
  "1014": "National Dessert Day",
  "1015": "National Grouch Day",
  "1016": "National Dictionary Day",
  "1017": "National Pasta Day",
  "1018": "National Chocolate Cupcake Day",
  "1019": "National Clean Your Virtual Desktop Day",
  "1020": "National Youth Confidence Day",
  "1021": "National Reptile Awareness Day",
  "1022": "National Nut Day",
  "1023": "National Boston Cream Pie Day",
  "1024": "National Bologna Day",
  "1025": "National Greasy Food Day",
  "1026": "National Pumpkin Day",
  "1027": "National Black Cat Day",
  "1028": "National Chocolate Day",
  "1029": "National Cat Day",
  "1030": "National Candy Corn Day",
  "1031": "National Knock-Knock Jokes Day",
  "1101": "National Family Literacy Day",
  "1102": "National Deviled Egg Day",
  "1103": "National Sandwich Day",
  "1104": "National Candy Day",
  "1105": "National Doughnut Day",
  "1106": "National Nachos Day",
  "1107": "National Bittersweet Chocolate with Almonds Day",
  "1108": "National STEM Day",
  "1109": "National Scrapple Day",
  "1110": "National Vanilla Cupcake Day",
  "1111": "Veterans Day",
  "1112": "National Pizza with the Works Except for Anchovies Day",
  "1113": "World Kindness Day",
  "1114": "National Pickle Day",
  "1115": "National Philanthropy Day",
  "1116": "National Button Day",
  "1117": "National Homemade Bread Day",
  "1118": "National Mickey Mouse Day",
  "1119": "National Play Monopoly Day",
  "1120": "National Absurdity Day",
  "1121": "National Gingerbread Cookie Day",
  "1122": "National Cranberry Relish Day",
  "1123": "National Cashew Day",
  "1124": "National Sardines Day",
  "1125": "National Parfait Day",
  "1126": "National Cake Day",
  "1127": "National Craft Jerky Day",
  "1128": "National French Toast Day",
  "1129": "National Electronic Greetings Day",
  "1130": "Computer Security Day",
  "1201": "National Eat a Red Apple Day",
  "1202": "National Fritters Day",
  "1203": "National Roof Over Your Head Day",
  "1204": "National Cookie Day",
  "1205": "National Sacher Torte Day",
  "1206": "National Microwave Oven Day",
  "1207": "National Cotton Candy Day",
  "1208": "National Brownie Day",
  "1209": "National Pastry Day",
  "1210": "National Dewey Decimal System Day",
  "1211": "National Noodle Ring Day",
  "1212": "National Ambrosia Day",
  "1213": "National Violin Day",
  "1214": "National Bouillabaisse Day",
  "1215": "National Cupcake Day",
  "1216": "National Chocolate-covered Anything Day",
  "1217": "National Maple Syrup Day",
  "1218": "National Answer The Telephone Like Buddy The Elf Day",
  "1219": "National Hard Candy Day",
  "1220": "National Ugly Christmas Sweater Day",
  "1221": "National Crossword Puzzle Day",
  "1222": "National Date Nut Bread Day",
  "1223": "National Roots Day",
  "1224": "National Eggnog Day",
  "1225": "National Pumpkin Pie Day",
  "1226": "National Thank-you Note Day",
  "1227": "National Fruitcake Day",
  "1228": "National Card Playing Day",
  "1229": "National Pepper Pot Day",
  "1230": "National Bicarbonate of Soda Day",
  "1231": "National Champagne Day",
}

/** Todays national day for a given Date (America/Denver via the caller). */
export function nationalDayFor(mmdd: string): string | null {
  return NATIONAL_DAYS[mmdd] ?? null
}
