// Shared context object passed to every extracted production-detail tab.
// All values originate in the parent page's render scope (state, handlers,
// computed locals). Typed loosely on purpose: this is a pure-extraction seam,
// and tsc still enforces that every referenced field is present in the object.
/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Dispatch, SetStateAction } from 'react'
import type { Production, ChecklistItem, ProductionMember, TeamMember, SchoolBrand, ProductionLink, KBArticle, ActivityItem, CameraPackageRow, LinkedVideo, LinkedTask, ProdLite } from '../page'

export interface PTabCtx {
  THUMB_EVENT_TYPES: readonly string[]
  THUMB_MASCOT_MODES: readonly string[]
  THUMB_TONES: readonly string[]
  activity: ActivityItem[]
  addKBLink: any
  addLink: any
  addMember: any
  addingMember: any
  allProductions: ProdLite[]
  allTeam: TeamMember[]
  assignSuccess: any
  border: any
  brandTone: any
  buildThumbnailPreviewDoc: any
  callSheet: any
  cameraOptionIdFromProduction: any
  cameraPackages: CameraPackageRow[]
  cardBg: any
  checklist: ChecklistItem[]
  clearThumbnailDraft: any
  completedCount: any
  copySetupTo: any
  copyTargetId: any
  copyThumbPrompt: any
  createTaskForProduction: any
  currentUser: TeamMember | null
  dangerTone: any
  dark: any
  delivCount: any
  delivNotes: any
  downloadThumbnailPng: any
  downloadThumbnailSvg: any
  effectiveProdStatus: any
  emailCallSheet: any
  externalCostUsd: any
  fetchingYt: any
  formatDateTime: any
  formatOutsourcedUsd: any
  formatRawCreatedOn: any
  generateCallSheet: any
  generatingSheet: any
  getTypeLabel: any
  infoTone: any
  initChecklist: any
  inputBg: any
  inputStyle: any
  isOnBehalf: any
  kbArticles: KBArticle[]
  linkYoutubeVideo: any
  linkedTasks: LinkedTask[]
  linkedVideos: LinkedVideo[]
  links: ProductionLink[]
  loadData: any
  massAssign: any
  memberToAdd: any
  members: ProductionMember[]
  missingThumbFields: any
  moveItem: any
  muted: any
  newLinkTitle: any
  newLinkUrl: any
  newTaskAssignee: any
  newTaskDue: any
  newTaskHideFromSignage: any
  newTaskPriority: any
  newTaskPurchaseLink: any
  newTaskPurchaseRequest: any
  newTaskTitle: any
  nonMembers: TeamMember[]
  notesSaved: any
  organizerEmail: any
  organizerName: any
  persistExternalCostFromInput: any
  printCallSheet: any
  production: Production
  progress: any
  recomputeOneEstimatedCost: any
  recomputingEstCost: any
  refreshYoutubeStats: any
  removeMember: any
  saveTeamNotes: any
  saveVideosProduced: any
  savingDeliv: any
  savingExternalCost: any
  savingNotes: any
  schools: SchoolBrand[]
  selectedKB: any
  selectedMember: any
  setAddingMember: any
  setChecklist: Dispatch<SetStateAction<ChecklistItem[]>>
  setCopyTargetId: any
  setDelivCount: any
  setDelivNotes: any
  setExternalCostUsd: any
  setLinkedVideos: Dispatch<SetStateAction<LinkedVideo[]>>
  setMemberToAdd: any
  setNewLinkTitle: any
  setNewLinkUrl: any
  setNewTaskAssignee: Dispatch<SetStateAction<string>>
  setNewTaskDue: any
  setNewTaskHideFromSignage: any
  setNewTaskPriority: any
  setNewTaskPurchaseLink: any
  setNewTaskPurchaseRequest: any
  setNewTaskTitle: any
  setSelectedKB: any
  setSelectedMember: any
  setShowCopySetup: any
  setShowCreateTask: Dispatch<SetStateAction<boolean>>
  setShowKBLink: any
  setShowLinkForm: any
  setTeamNotes: any
  setThumbConceptAnchor: any
  setThumbDate: any
  setThumbDetail: any
  setThumbEventDescription: any
  setThumbEventName: any
  setThumbEventType: any
  setThumbLogistics: any
  setThumbMascotMode: any
  setThumbPrompt: any
  setThumbSchoolCode: any
  setThumbSchoolOverride: any
  setThumbSvgInput: any
  setThumbTime: any
  setThumbTone: any
  setYoutubeUrl: any
  showCopySetup: any
  showCreateTask: any
  showKBLink: any
  showLinkForm: any
  showSubmitterCard: any
  submitterEmail: any
  submitterName: any
  successTone: any
  supabase: any
  teamNotes: any
  text: any
  thumbConceptAnchor: any
  thumbCopied: any
  thumbDate: any
  thumbDetail: any
  thumbDraftRestored: any
  thumbDraftSavedAt: any
  thumbEventDescription: any
  thumbEventName: any
  thumbEventType: any
  thumbLogistics: any
  thumbMascotMode: any
  thumbPrompt: any
  thumbSanitizedSvg: any
  thumbSchoolCode: any
  thumbSchoolOverride: any
  thumbSvgError: any
  thumbSvgInput: any
  thumbTime: any
  thumbTone: any
  toggleItem: any
  typeLabel: any
  uuid: any
  warningTone: any
  youtubeUrl: any
}
