-- Schema doctor: READ-ONLY. Run in Supabase SQL editor.
-- Returns the tables/columns the code expects that are MISSING from your DB.
-- Zero rows = you are fully migrated. Each row tells you what to add.
with expected_tables(t) as (values
('board_bell_settings'),
('board_meeting_agenda_documents'),
('board_meeting_agenda_items'),
('board_meeting_presenters'),
('board_meetings'),
('channel_assignments'),
('impersonation_audit'),
('impersonation_sessions'),
('lower_third_groups'),
('lower_third_people'),
('media_assets'),
('meeting_attendance'),
('meeting_broadcast_state'),
('meeting_event_log'),
('meeting_motion_votes'),
('meeting_motions'),
('meeting_playlist_items'),
('meeting_playlists'),
('meeting_timers'),
('onboarding_assignments'),
('onboarding_categories'),
('onboarding_item_instances'),
('onboarding_phases'),
('onboarding_template_items'),
('onboarding_tracks'),
('output_channels'),
('playlist_template_items'),
('playlist_templates'),
('project_ideas'),
('qr_presets'),
('quick_links'),
('signage_announcements'),
('signage_areas'),
('signage_board_takeover'),
('signage_content'),
('signage_live'),
('signage_screens'),
('signage_settings'),
('signage_site_access'),
('signage_sites'),
('signage_visitors'),
('signage_wayfinding'),
('task_assignments'),
('task_intake_tokens'),
('task_recurrence_assignees'),
('task_recurrences'),
('timer_templates')
),
expected_cols(t,c) as (values
('board_meeting_agenda_items','live_status'),
('board_meeting_agenda_items','suggested_motion_text'),
('board_meeting_presenters','affiliation'),
('board_meetings','live_started_at'),
('board_meetings','public_agenda_url'),
('board_meetings','stream_started_at'),
('equipment','is_power_cable'),
('equipment','parent_equipment_id'),
('equipment','power_barrel_size'),
('equipment','power_brand'),
('equipment','power_input_connector'),
('equipment','power_output_amperage'),
('equipment','power_output_polarity'),
('equipment','power_output_voltage'),
('meeting_broadcast_state','active_lower_third_person_id'),
('meeting_broadcast_state','active_motion_id'),
('meeting_broadcast_state','active_qr_duration_seconds'),
('meeting_broadcast_state','active_qr_label'),
('meeting_broadcast_state','active_qr_started_at'),
('meeting_broadcast_state','active_qr_url'),
('meeting_broadcast_state','active_vote_result_motion_id'),
('meeting_broadcast_state','agenda_branding_hold'),
('meeting_broadcast_state','elapsed_started_at'),
('meeting_broadcast_state','lower_third_position'),
('meeting_broadcast_state','vote_result_duration_seconds'),
('meeting_broadcast_state','vote_result_held'),
('meeting_broadcast_state','vote_result_started_at'),
('meeting_motions','result'),
('meeting_motions','tally_absent'),
('meeting_motions','tally_abstain'),
('meeting_motions','tally_nay'),
('meeting_motions','tally_recused'),
('meeting_motions','tally_yea'),
('school_brand_colors','city'),
('school_brand_colors','link_url'),
('school_brand_colors','mascot_name'),
('school_brand_colors','text_color'),
('school_brand_colors','title_i'),
('schools','city'),
('schools','link_url'),
('schools','mascot_name'),
('schools','text_color'),
('schools','title_i'),
('signage_announcements','area_id'),
('signage_announcements','pending'),
('signage_announcements','site_id'),
('signage_announcements','submitter_email'),
('signage_announcements','submitter_name'),
('signage_areas','site_id'),
('signage_board_takeover','heartbeat_at'),
('signage_content','site_id'),
('signage_screens','board_takeover_audio'),
('signage_screens','board_takeover_enabled'),
('signage_screens','pos_x'),
('signage_screens','pos_y'),
('signage_screens','site_id'),
('signage_screens','theme'),
('signage_settings','default_theme'),
('signage_sites','accent_color'),
('signage_sites','bg_color'),
('signage_sites','panel_color'),
('signage_sites','text_color'),
('signage_visitors','area_id'),
('signage_visitors','pending'),
('signage_visitors','site_id'),
('signage_visitors','submitter_email'),
('signage_visitors','submitter_name'),
('signage_wayfinding','site_id'),
('task_intake_tokens','token_plain'),
('tasks','hide_from_signage'),
('tasks','intake_source'),
('tasks','intake_submitter_email'),
('tasks','intake_submitter_name'),
('tasks','intake_token_id'),
('tasks','purchase_request'),
('tasks','purchase_request_link'),
('tasks','recurrence_cycle_date'),
('tasks','recurrence_id'),
('team','signage_approver')
),
missing_tables as (
  select 'MISSING TABLE' as issue, t as table_name, '' as column_name
  from expected_tables where to_regclass('public.'||t) is null
),
missing_cols as (
  select 'missing column' as issue, ec.t as table_name, ec.c as column_name
  from expected_cols ec
  where to_regclass('public.'||ec.t) is not null
    and not exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name=ec.t and column_name=ec.c
    )
)
select * from missing_tables
union all select * from missing_cols
order by 1,2,3;
